Fix #8
vaadin-component-factory/selection-grid-pro-flow pull request #9
Opened 2024-06-24 20:44 UTC by mlopezFC

2024-06-24 21:44 UTC, javier-godoy commented
The suggested approach improves the performance when the requested item is already present in the key mapper. However, if the user selects a row, scrolls down and then selects another row, it will result in N separate fetches instead of a single one.

2024-06-24 21:45 UTC, javier-godoy commented on selection-grid-pro-flow/src/main/java/com/vaadin/componentfactory/selectiongridpro/SelectionGridPro.java
> +            for(int i = Math.min(fromIndex, toIndex); i < (Math.max(fromIndex,
There is no need to compute this value in each iteration.

2024-06-25 11:35 UTC, mlopezFC commented on selection-grid-pro-flow/src/main/java/com/vaadin/componentfactory/selectiongridpro/SelectionGridPro.java
> +            for(int i = Math.min(fromIndex, toIndex); i < (Math.max(fromIndex,
Fixed ✔️

2024-06-26 15:16 UTC, javier-godoy requested changes

2024-06-26 15:16 UTC, javier-godoy commented on selection-grid-pro-flow/src/main/java/com/vaadin/componentfactory/selectiongridpro/SelectionGridPro.java
> +		if (to - from < (pageSize * 2) - 3) {
Please add a comment explaining the reasoning behind this condition.

2024-06-26 19:40 UTC, mlopezFC commented on selection-grid-pro-flow/src/main/java/com/vaadin/componentfactory/selectiongridpro/SelectionGridPro.java
> +		if (to - from < (pageSize * 2) - 3) {
Done ✔️

2024-06-26 19:50 UTC, javier-godoy approved these changes

2024-06-26 19:50 UTC, merged